[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bonesistools"
description = "python package proposing functionnalities and analysis upstream and downstream of BoNesis framework"
version = "1.0.0"
dynamic = [ "version" ]
authors = [
    { name = "Théo Roncalli" },
    { name = "Loïc Paulevé" },
]
maintainers = [
    { name = "Théo Roncalli", email = "theo.roncalli@labri.fr" },
]
readme = "README.md"
classifiers = [
    "Environment :: Console",
    "Framework :: IPython",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Software Development :: Build Tools",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Scientific/Engineering :: Boolean Networks",
]
requires-python = ">=3.7"
dependencies = [
    "anndata>=0.8",
    "ctypes>=1.1.0",
    "h5py>=3.7",
    "matplotlib>=3.5",
    "networkx>=2.1",
    "numpy>=1.21",
    "pandas >=1.3.5",
    "scikit-learn>=1.0",
    "scipy>=1.7",
]
keywords = [
    "bonesis",
    "rnaseq",
    "h5py",
    "anndata",
    "scanpy",
    "sctools",
]

[project.optional-dependencies]
collectri = [ "decoupler>=1.8" ]
mudata = [ "mudata" ]

[project.urls]
Repository = "https://github.com/bnediction/bonesistools"