[pytest]
addopts = -l -ra --strict-markers --strict-config
testpaths =
    tests/regression
norecursedirs =
    tests/reproducibility
filterwarnings =
    ignore:The NumPy module was reloaded:UserWarning
