[pytest]
addopts = -l -ra --strict-markers --strict-config
testpaths =
    tests/regression
norecursedirs =
    tests/reproducibility
filterwarnings =
    ignore:The NumPy module was reloaded:UserWarning
    ignore:The decorator_name argument is deprecated.*:DeprecationWarning:mudata
    ignore:The docstring_style argument is deprecated.*:DeprecationWarning:mudata
