name: tests

on:
  push:
  pull_request:

jobs:
  import-test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package
        run: pip install -e .

      - name: Check import
        run: python -c "import bonesistools"

  full-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install package with all extras
        run: pip install -e ".[all]"

      - name: Install test dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest